# Porta del server Web per l'interfaccia grafica
server.port=8080

# Nome logico dell'applicazione
spring.application.name=web-portal

# URL dei microservizi di backend
backend.auth-service.url=http://localhost:8081/api/auth
backend.student-service.url=http://localhost:8082/api/students
backend.exam-service.url=http://localhost:8083/api/exams

# Disabilita la cache di Thymeleaf per vedere le modifiche alle pagine HTML all'istante senza dover riavviare il server
spring.thymeleaf.cache=false